### ISSUE TITLE
disk_size_MB is actually GB

### ISSUE THREAD

**Issue by camrossi** [noironetworks/openshift_vsphere_upi#16]
In the [group_vars/all.yml](https://github.com/noironetworks/openshift_vsphere_upi/blob/master/group_vars/all.yml) config file we set the VMs disk size with a variable called `disk_size_MB` this is then passed to the terraform  `vsphere_virtual_machine` disk.size attribute. 

The disk.size attribute is specified in GB, so the `disk_size_MB` variable should be renamed to `disk_size_GB`

**Comment by PariyaAshok** [comment]
Yes, Similarly memory_KB should be renamed to memory_MB.

**Comment by camrossi** [comment]
Oh I didn't notice that one but yes let's fix them both !

**Comment by PariyaAshok** [comment]
PR: https://github.com/noironetworks/openshift_vsphere_upi/pull/17
