### ISSUE TITLE
ACI CISCO + OKD 4.5 or 6

### ISSUE THREAD

**Issue by jmateusousa** [noironetworks/openshift_vsphere_upi#2]
Staff,

We are trying to implement an openshift cluster OKD 4.5 or 6 + Fedora coreOS 33.20210217.3.0, using this repository as a base, we have direct access to the internet without a proxy.

We were able to initialize all the machines, bootstrap, masters and workers, but the deployment does not end, the masters are ready, but the only operators who went up were the Cloud-credential network, workers were not able to go into production, they are on the boot, trying to fetch your boot settings and we have no feedback on completing the bootstrap configuration (timeout)

have you already been successful in integrating ACI + OKD?

could you guide us about this implementation?

Thanks.
![log1](https://user-images.githubusercontent.com/18659233/109804669-45099700-7c01-11eb-9dfe-6f7e233d64b6.png)
![co](https://user-images.githubusercontent.com/18659233/109804496-112e7180-7c01-11eb-9227-023565577977.png)
![pods_aci](https://user-images.githubusercontent.com/18659233/109803942-7170e380-7c00-11eb-82fc-4ef6b34325d6.png)
![pods_erro](https://user-images.githubusercontent.com/18659233/109803947-72a21080-7c00-11eb-81a2-8e1647bd88c2.png)

**Comment by ratnakark** [comment]
Hello,

The problem seems to be that aci-containers-host and
aci-containers-controller are crashing. It would be helpful in getting the
logs for these containers to debug further. (One of the problems could be
that the MTU on the opflex interface is  not set correct, the logs would
confirm that if it happens to be the case.)

THanks,
==ratnakar

**Comment by jmateusousa** [comment]
Hello ratnakar,

I managed to get some logs from the container, below is evidence for viewing.

#aci-containeres-controller
![controller_events](https://user-images.githubusercontent.com/18659233/110162388-6fa84b00-7dcd-11eb-8d43-d107ac4409e3.png)

#aci-containers-host
![erro_container](https://user-images.githubusercontent.com/18659233/110162393-71720e80-7dcd-11eb-904f-022f2af5913d.png)

and I noticed a flaw in the masters ens224 network interface which is precisely the second interface connected in these vms that is in vlan 3967

master and nodes have two interfaces
OCP_4001 - VLAN ID 4001
OCP - VLAN - trunk range 4001, 3967, 4002

bootstrap, lb and orchetrator with only one interface
OCP - VLAN trunk range 4001, 3967, 4002

![interfaces](https://user-images.githubusercontent.com/18659233/110162396-720aa500-7dcd-11eb-91d8-a4116f1cbd18.png)

a doubt this second OCP - VLAN interface would need a dhcp for ips delivery? I am waiting for feedback from the network team to check the MTU issue

Thank's!!

**Comment by jmateusousa** [comment]
Provisioning done successfully, thanks for your help
